//This file is used to define servos, servo positions, and motors

#pragma once
#pragma systemFile

#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// drive motor definitions
const tMotor RIGHT_DRIVE_MOTOR = motorD;
const tMotor LEFT_DRIVE_MOTOR = motorE;

// spinner motors
const tMotor RIGHT_SPINNER = motorF;
const tMotor LEFT_SPINNER = motorG;

// the dumper servo on the schlorp tube
const TServoIndex DUMP_SERVO = servo1;
const int DUMP_UP = 0;
const int DUMP_DOWN = 140;

// right servo for grabbing tubes
const TServoIndex RIGHT_TUBE_SERVO = servo2;
const int RIGHT_TUBE_UP = 127;
const int RIGHT_TUBE_DOWN = 240;

// left servo for grabbing tubes
const TServoIndex LEFT_TUBE_SERVO = servo3;
const int LEFT_TUBE_UP = 127;
const int LEFT_TUBE_DOWN = 15;

// resets the positions of all the servos
void resetPositions()
{
	servo[DUMP_SERVO] = DUMP_UP;
	servo[RIGHT_TUBE_SERVO] = RIGHT_TUBE_DOWN;
	servo[LEFT_TUBE_SERVO] = LEFT_TUBE_DOWN;
}
