#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Gyro.h"
#include "PID.h"
#include "motorControl.h"

task main()
{
	Gyro g;
	initGyro(g, S2);
	calibrateGyro(g);
	PID pid;
	initPID(pid, 1, 0.0000000001, 3, T2);

	setPIDTarget(pid, 90);

	while(true)
	{
		float currentPidValue = getPIDValue(pid, g.heading);
		displayTextLine(1, "heading: %d", g.heading);
		displayTextLine(2, "PID error: %d", pid.lastError);
		displayTextLine(3, "value: %d", currentPidValue);
		turn(-currentPidValue);
		//wait1Msec(10);
		updateGyro(g);
	}
}
