#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     RIGHT_DRIVE_MOTOR, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     LEFT_DRIVE_MOTOR, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    armServo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickButtons.h"
#include "JoystickDriver.c"
#include "DriverUtils.h"

bool fire = false;

bool rightDead = true;
bool leftDead = true;
task armControl()
{
	while(true)
	{
		servoChangeRate[armServo] = 0;
		servo[armServo] = 50;
		if(fire)
		{
			servo[armServo] = 100;
			wait1Msec(700);
			fire = false;
		}
	}
}


task main()
{
	startTask(armControl);
	waitForStart();
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy1Btn(BTN_A))
		{
			fire = true;
		}
		if(abs(joystick.joy1_y2) >= 5)	//if the right joystick is moved
		{
			rightDead = false;	//then the controler is not in deadzone
			if(joystick.joy1_y2 > 0)
				motor[LEFT_DRIVE_MOTOR] = exponentialDrive(joystick.joy1_y2);	//sets the motor power to the joystick reading
			else
				motor[LEFT_DRIVE_MOTOR] = exponentialDrive(joystick.joy1_y2);
		}
		else	//if the joysitck is in the deadzone
		{
			rightDead = true;	//sets the variable to true
		}
		if(abs(joystick.joy1_y1) >= 5)	//if the left joystick is moved
		{
			leftDead = false;	//then the controler is not in deadzone
			if(joystick.joy1_y1 > 0)
				motor[RIGHT_DRIVE_MOTOR] = exponentialDrive(joystick.joy1_y1);	//sets the motor power to the joystick reading
			else
				motor[RIGHT_DRIVE_MOTOR] = exponentialDrive(joystick.joy1_y1);
		}
		else
		{
			leftDead = true;
		}

		if(rightDead && leftDead)
		{
			motor[RIGHT_DRIVE_MOTOR] = 0;
			motor[LEFT_DRIVE_MOTOR] = 0;
		}
	}
}
